image: "python:3.7"

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_STRATEGY: clone
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache: &global_cache
  paths:
    - .cache/pip
    - venv/
  key: ${CI_COMMIT_REF_SLUG}
  policy: pull-push

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - python -m pip install --upgrade pip 
  - pip install -r requirements.txt 
  - pip install flake8 

stages:
  - build
  - test

build_isct:
  stage: build
  cache:
    <<: *global_cache
    policy: push
  script:
    - pip install -e .

test_isct:
  stage: test
  cache:
    <<: *global_cache
    policy: pull
  script:
    - pytest --cov=workflow

flake8_isct:
  stage: test
  cache:
    <<: *global_cache
    policy: pull
  script: 
    - flake8 workflow
