image: "python:3.7"

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_STRATEGY: clone

stages: 
  - build
  - test 

before_script: 
  - python --version

build_isct: 
  stage: build 
  script: 
    - pip install -e . 
    - pip install -r requirements.txt

test_isct: 
  stage: test
  script: 
    - pytest 
