image: "python:3.7"

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_STRATEGY: clone

cache:
  paths:
    - patient/
  key: "$CI_PIPELINE_ID"

stages: 
  - build 
  - test 

before_script: 
  - python --version

build_isct: 
  stage: build 
  script: 
    - pip install -e . 
    - pip install -r requirements.txt

build_containers: 
  stage: build
  script: 
    - docker build . -t "in-silico-trial"
    - ./scripts/create_containers.sh  
    - rm ./workflow/docker_image_list 

test_isct: 
  stage: test
  script: 
    - pytest 
