image: "python:3.9"

variables:
  GIT_SUBMODULE_STRATEGY: none
  GIT_STRATEGY: fetch
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache: &global_cache
  key: pip-isct
  paths:
    - .cache/pip

before_script:
  - python -V
  - python -m pip install --upgrade pip setuptools wheel
  - pip install --cache-dir=.cache/pip tox

stages:
  - build
  - test

build_isct:
  stage: build
  script:
    - pip install -e .[all]

test_isct:
  stage: test
  script:
    - tox -e py39

test_isct_38:
  # ensure the code runs on 3.8 as well
  image: "python:3.8"
  stage: test
  script:
    - tox -e py38

test_isct_vvuq:
  stage: test
  script:
    - tox -e py39-vvuq

lint_isct:
  stage: test
  script:
    - tox -e flake8
