image: "python:3.7"

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_STRATEGY: clone
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

stages:
  - build
  - test

build_isct:
  stage: build
  script:
    - pip install -e .
    - pip install -r requirements.txt
    - pip install flake8

test_isct:
  stage: test
  script:
    - pytest --cov=workflow

flake8_isct:
  stage: test
  script: 
    - flake8 workflow
